//-----------------------------------------------------------------------
// <copyright file="TestReport.h">
//      Copyright (c) Microsoft Corporation. All rights reserved.
// 
//      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
//      EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
//      MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
//      IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
//      CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
//      TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
//      SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// </copyright>
//-----------------------------------------------------------------------

#ifndef MICROSOFT_P3_TESTINGSERVICES_STATISTICS_TESTREPORT_H
#define MICROSOFT_P3_TESTINGSERVICES_STATISTICS_TESTREPORT_H

namespace Microsoft { namespace P3 { namespace TestingServices
{
    // Test report generated by the bug-finding engine.
    class TestReport
    {
    public:
        // Number of found bugs.
        int NumOfFoundBugs;

        TestReport();
        ~TestReport();
    };
} } }

#endif // MICROSOFT_P3_TESTINGSERVICES_STATISTICS_TESTREPORT_H
